name: Build and Release Module

on:
  push:
    branches: [ main, dev ]  # Se ejecuta al subir cambios a las ramas main o dev
  pull_request:
    branches: [ main, dev ]  # Se ejecuta al abrir un pull request hacia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instalamos build para el empaquetado y pytest para los tests
        # También instalamos las librerías que usan tus scripts (pandas, etc.)
        pip install build pytest pandas numpy 
        # Instalamos tu proyecto en modo editable para que los tests encuentren 'modulo_analitics'
        pip install -e .

    - name: Run Tests
      run: |
        # Ejecuta todos los tests dentro de la carpeta Tests
        pytest Tests/

    - name: Build package
      # Este paso solo se ejecutará si 'Run Tests' tiene éxito (check verde)
      run: python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package-dist
        path: dist/